//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySoft.Core.Util.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UtilResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UtilResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySoft.Core.Util.Resources.UtilResource", typeof(UtilResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 提交失败，错误信息 的本地化字符串。
        /// </summary>
        public static string Message_SubmitFailed {
            get {
                return ResourceManager.GetString("Message_SubmitFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数[{0}]无效 的本地化字符串。
        /// </summary>
        public static string Validate_ArgumentInValid {
            get {
                return ResourceManager.GetString("Validate_ArgumentInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入{0}，值为[{1} - {2}]之间的整数或小数 的本地化字符串。
        /// </summary>
        public static string Validate_DecimalFieldRange {
            get {
                return ResourceManager.GetString("Validate_DecimalFieldRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入{0}，字数在[{1} - {2}]个之间 的本地化字符串。
        /// </summary>
        public static string Validate_FieldLengthOverflow {
            get {
                return ResourceManager.GetString("Validate_FieldLengthOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入{0}，最多{1}个字 的本地化字符串。
        /// </summary>
        public static string Validate_FieldMaxLength {
            get {
                return ResourceManager.GetString("Validate_FieldMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入{0}，最少{1}个字 的本地化字符串。
        /// </summary>
        public static string Validate_FieldMinLength {
            get {
                return ResourceManager.GetString("Validate_FieldMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入{0}，值为[{1} - {2}]之间的整数 的本地化字符串。
        /// </summary>
        public static string Validate_IntFieldRange {
            get {
                return ResourceManager.GetString("Validate_IntFieldRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}数据为空 的本地化字符串。
        /// </summary>
        public static string Validate_ListDataIsEmpty {
            get {
                return ResourceManager.GetString("Validate_ListDataIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入格式为yyyy-MM-dd的日期字符串 的本地化字符串。
        /// </summary>
        public static string Validate_PleaseInputDateString {
            get {
                return ResourceManager.GetString("Validate_PleaseInputDateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入{0} 的本地化字符串。
        /// </summary>
        public static string Validate_PleaseInputField {
            get {
                return ResourceManager.GetString("Validate_PleaseInputField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择{0} 的本地化字符串。
        /// </summary>
        public static string Validate_PleaseSelectField {
            get {
                return ResourceManager.GetString("Validate_PleaseSelectField", resourceCulture);
            }
        }
    }
}
