//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySoft.PssS.Domain.Service {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BusinessResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BusinessResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySoft.PssS.Domain.Service.BusinessResource", typeof(BusinessResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 未找到指定Id的数据记录。 的本地化字符串。
        /// </summary>
        internal static string Common_NoFoundById {
            get {
                return ResourceManager.GetString("Common_NoFoundById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态已经变更，不允许删除。 的本地化字符串。
        /// </summary>
        internal static string Common_NotAllowDelete {
            get {
                return ResourceManager.GetString("Common_NotAllowDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态已经变更，不允许修改。 的本地化字符串。
        /// </summary>
        internal static string Common_NotAllowEdit {
            get {
                return ResourceManager.GetString("Common_NotAllowEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相同编码的成本项已存在。 的本地化字符串。
        /// </summary>
        internal static string CostItem_ExistsSameCode {
            get {
                return ResourceManager.GetString("CostItem_ExistsSameCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相同名称的分组已存在。 的本地化字符串。
        /// </summary>
        internal static string Customer_ExistsSameGroupName {
            get {
                return ResourceManager.GetString("Customer_ExistsSameGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到指定的客户数据记录。 的本地化字符串。
        /// </summary>
        internal static string Customer_NoFound {
            get {
                return ResourceManager.GetString("Customer_NoFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到指定的客户地址数据记录。 的本地化字符串。
        /// </summary>
        internal static string Customer_NoFoundAddress {
            get {
                return ResourceManager.GetString("Customer_NoFoundAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到默认分组Id。 的本地化字符串。
        /// </summary>
        internal static string Customer_NoFoundDefaultGroupId {
            get {
                return ResourceManager.GetString("Customer_NoFoundDefaultGroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到指定的客户分组数据记录。 的本地化字符串。
        /// </summary>
        internal static string Customer_NoFoundGroup {
            get {
                return ResourceManager.GetString("Customer_NoFoundGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认分组不允许删除。 的本地化字符串。
        /// </summary>
        internal static string Customer_NotAllowDeleteCustomerGroup {
            get {
                return ResourceManager.GetString("Customer_NotAllowDeleteCustomerGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认地址不允许删除。 的本地化字符串。
        /// </summary>
        internal static string Customer_NotAllowDeleteDefaultAddress {
            get {
                return ResourceManager.GetString("Customer_NotAllowDeleteDefaultAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到指定的出库数据记录。 的本地化字符串。
        /// </summary>
        internal static string Delivery_NoFoundById {
            get {
                return ResourceManager.GetString("Delivery_NoFoundById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相同编码的快递公司已存在。 的本地化字符串。
        /// </summary>
        internal static string ExpressCompany_ExistsSameCode {
            get {
                return ResourceManager.GetString("ExpressCompany_ExistsSameCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 库存不足。 的本地化字符串。
        /// </summary>
        internal static string Purchase_LowStocks {
            get {
                return ResourceManager.GetString("Purchase_LowStocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到指定Id的采购数据记录。 的本地化字符串。
        /// </summary>
        internal static string Purchase_NoFoundById {
            get {
                return ResourceManager.GetString("Purchase_NoFoundById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相同编码的采购项已存在。 的本地化字符串。
        /// </summary>
        internal static string PurchaseItem_ExistsSameCode {
            get {
                return ResourceManager.GetString("PurchaseItem_ExistsSameCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选中的客户地址无效。 的本地化字符串。
        /// </summary>
        internal static string SaleOrder_CustomerAddressInvalid {
            get {
                return ResourceManager.GetString("SaleOrder_CustomerAddressInvalid", resourceCulture);
            }
        }
    }
}
