//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySoft.PssS.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WebResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySoft.PssS.Web.Resources.WebResource", typeof(WebResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 返回 的本地化字符串。
        /// </summary>
        public static string Button_Back {
            get {
                return ResourceManager.GetString("Button_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string Button_Delete {
            get {
                return ResourceManager.GetString("Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改 的本地化字符串。
        /// </summary>
        public static string Button_Edit {
            get {
                return ResourceManager.GetString("Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入库 的本地化字符串。
        /// </summary>
        public static string Button_Into {
            get {
                return ResourceManager.GetString("Button_Into", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 立即登录 的本地化字符串。
        /// </summary>
        public static string Button_Login {
            get {
                return ResourceManager.GetString("Button_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报损 的本地化字符串。
        /// </summary>
        public static string Button_Loss {
            get {
                return ResourceManager.GetString("Button_Loss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string Button_Ok {
            get {
                return ResourceManager.GetString("Button_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        public static string Button_Out {
            get {
                return ResourceManager.GetString("Button_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出库 的本地化字符串。
        /// </summary>
        public static string Button_Output {
            get {
                return ResourceManager.GetString("Button_Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报溢/报损 的本地化字符串。
        /// </summary>
        public static string Button_OverOrLoss {
            get {
                return ResourceManager.GetString("Button_OverOrLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报益 的本地化字符串。
        /// </summary>
        public static string Button_Profit {
            get {
                return ResourceManager.GetString("Button_Profit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交 的本地化字符串。
        /// </summary>
        public static string Button_Submit {
            get {
                return ResourceManager.GetString("Button_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看 的本地化字符串。
        /// </summary>
        public static string Button_View {
            get {
                return ResourceManager.GetString("Button_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看更多 &gt;&gt; 的本地化字符串。
        /// </summary>
        public static string Button_ViewMore {
            get {
                return ResourceManager.GetString("Button_ViewMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 明细 的本地化字符串。
        /// </summary>
        public static string Common_Detail {
            get {
                return ResourceManager.GetString("Common_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 。 的本地化字符串。
        /// </summary>
        public static string Common_FullStop {
            get {
                return ResourceManager.GetString("Common_FullStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无 的本地化字符串。
        /// </summary>
        public static string Common_None {
            get {
                return ResourceManager.GetString("Common_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 元 的本地化字符串。
        /// </summary>
        public static string Common_Yuan {
            get {
                return ResourceManager.GetString("Common_Yuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消按钮 的本地化字符串。
        /// </summary>
        public static string Dialog_CancelButton {
            get {
                return ResourceManager.GetString("Dialog_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定字符串 的本地化字符串。
        /// </summary>
        public static string Dialog_ConfirmString {
            get {
                return ResourceManager.GetString("Dialog_ConfirmString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对话框Id 的本地化字符串。
        /// </summary>
        public static string Dialog_Id {
            get {
                return ResourceManager.GetString("Dialog_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消息体Id 的本地化字符串。
        /// </summary>
        public static string Dialog_MessageBodyId {
            get {
                return ResourceManager.GetString("Dialog_MessageBodyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定按钮 的本地化字符串。
        /// </summary>
        public static string Dialog_OkButton {
            get {
                return ResourceManager.GetString("Dialog_OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对话框标题 的本地化字符串。
        /// </summary>
        public static string Dialog_Title {
            get {
                return ResourceManager.GetString("Dialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地址 的本地化字符串。
        /// </summary>
        public static string Field_Address {
            get {
                return ResourceManager.GetString("Field_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基本信息 的本地化字符串。
        /// </summary>
        public static string Field_BasicInfo {
            get {
                return ResourceManager.GetString("Field_BasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ： 的本地化字符串。
        /// </summary>
        public static string Field_Colon {
            get {
                return ResourceManager.GetString("Field_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成本 的本地化字符串。
        /// </summary>
        public static string Field_Cost {
            get {
                return ResourceManager.GetString("Field_Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成本项 的本地化字符串。
        /// </summary>
        public static string Field_CostItem {
            get {
                return ResourceManager.GetString("Field_CostItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成本项金额 的本地化字符串。
        /// </summary>
        public static string Field_CostItemMoney {
            get {
                return ResourceManager.GetString("Field_CostItemMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户Id 的本地化字符串。
        /// </summary>
        public static string Field_CustomerId {
            get {
                return ResourceManager.GetString("Field_CustomerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日期 的本地化字符串。
        /// </summary>
        public static string Field_Date {
            get {
                return ResourceManager.GetString("Field_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认地址 的本地化字符串。
        /// </summary>
        public static string Field_DefaultAddress {
            get {
                return ResourceManager.GetString("Field_DefaultAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分组 的本地化字符串。
        /// </summary>
        public static string Field_Group {
            get {
                return ResourceManager.GetString("Field_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Id 的本地化字符串。
        /// </summary>
        public static string Field_Id {
            get {
                return ResourceManager.GetString("Field_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 库存 的本地化字符串。
        /// </summary>
        public static string Field_Inventory {
            get {
                return ResourceManager.GetString("Field_Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目 的本地化字符串。
        /// </summary>
        public static string Field_Item {
            get {
                return ResourceManager.GetString("Field_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联系人 的本地化字符串。
        /// </summary>
        public static string Field_Linkman {
            get {
                return ResourceManager.GetString("Field_Linkman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手机号 的本地化字符串。
        /// </summary>
        public static string Field_Mobile {
            get {
                return ResourceManager.GetString("Field_Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 金额 的本地化字符串。
        /// </summary>
        public static string Field_Money {
            get {
                return ResourceManager.GetString("Field_Money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        public static string Field_Name {
            get {
                return ResourceManager.GetString("Field_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 昵称 的本地化字符串。
        /// </summary>
        public static string Field_Nickname {
            get {
                return ResourceManager.GetString("Field_Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        public static string Field_Password {
            get {
                return ResourceManager.GetString("Field_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 益损 的本地化字符串。
        /// </summary>
        public static string Field_ProfitLoss {
            get {
                return ResourceManager.GetString("Field_ProfitLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 益损类型 的本地化字符串。
        /// </summary>
        public static string Field_ProfitLossCategory {
            get {
                return ResourceManager.GetString("Field_ProfitLossCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 益损目标类型 的本地化字符串。
        /// </summary>
        public static string Field_ProfitLossTargetType {
            get {
                return ResourceManager.GetString("Field_ProfitLossTargetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 采购类型 的本地化字符串。
        /// </summary>
        public static string Field_PurchaseCategory {
            get {
                return ResourceManager.GetString("Field_PurchaseCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数量 的本地化字符串。
        /// </summary>
        public static string Field_Quantity {
            get {
                return ResourceManager.GetString("Field_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记录Id 的本地化字符串。
        /// </summary>
        public static string Field_RecordId {
            get {
                return ResourceManager.GetString("Field_RecordId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        public static string Field_Remark {
            get {
                return ResourceManager.GetString("Field_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设为默认 的本地化字符串。
        /// </summary>
        public static string Field_SetDefault {
            get {
                return ResourceManager.GetString("Field_SetDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 供应商 的本地化字符串。
        /// </summary>
        public static string Field_Supplier {
            get {
                return ResourceManager.GetString("Field_Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总资产(元) 的本地化字符串。
        /// </summary>
        public static string Field_TotalAssets {
            get {
                return ResourceManager.GetString("Field_TotalAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成本(元) 的本地化字符串。
        /// </summary>
        public static string Field_TotalCost {
            get {
                return ResourceManager.GetString("Field_TotalCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收益(元) 的本地化字符串。
        /// </summary>
        public static string Field_TotalIncome {
            get {
                return ResourceManager.GetString("Field_TotalIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 微信号 的本地化字符串。
        /// </summary>
        public static string Field_WeChatId {
            get {
                return ResourceManager.GetString("Field_WeChatId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有分组 的本地化字符串。
        /// </summary>
        public static string Message_AllGroup {
            get {
                return ResourceManager.GetString("Message_AllGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有项目 的本地化字符串。
        /// </summary>
        public static string Message_AllItem {
            get {
                return ResourceManager.GetString("Message_AllItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未传入参数。 的本地化字符串。
        /// </summary>
        public static string Message_ArgumentIsNull {
            get {
                return ResourceManager.GetString("Message_ArgumentIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认 的本地化字符串。
        /// </summary>
        public static string Message_Confirm {
            get {
                return ResourceManager.GetString("Message_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您确认要删除该数据吗？ 的本地化字符串。
        /// </summary>
        public static string Message_ConfirmDelete {
            get {
                return ResourceManager.GetString("Message_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        public static string Message_Error {
            get {
                return ResourceManager.GetString("Message_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信息 的本地化字符串。
        /// </summary>
        public static string Message_Info {
            get {
                return ResourceManager.GetString("Message_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在载入... 的本地化字符串。
        /// </summary>
        public static string Message_Loading {
            get {
                return ResourceManager.GetString("Message_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手机号或密码错误，请重新输入。 的本地化字符串。
        /// </summary>
        public static string Message_LoginError {
            get {
                return ResourceManager.GetString("Message_LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用手机号登录。 的本地化字符串。
        /// </summary>
        public static string Message_LoginTip {
            get {
                return ResourceManager.GetString("Message_LoginTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有数据 的本地化字符串。
        /// </summary>
        public static string Message_NoData {
            get {
                return ResourceManager.GetString("Message_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有数据都在上面了 的本地化字符串。
        /// </summary>
        public static string Message_NoMoreData {
            get {
                return ResourceManager.GetString("Message_NoMoreData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您访问的页面不存在，请返回上一页。 的本地化字符串。
        /// </summary>
        public static string Message_PageNotFound {
            get {
                return ResourceManager.GetString("Message_PageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交失败，错误信息 的本地化字符串。
        /// </summary>
        public static string Message_SubmitFailed {
            get {
                return ResourceManager.GetString("Message_SubmitFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 损耗 的本地化字符串。
        /// </summary>
        public static string ProfitLoss_Loss {
            get {
                return ResourceManager.GetString("ProfitLoss_Loss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 增益 的本地化字符串。
        /// </summary>
        public static string ProfitLoss_Profit {
            get {
                return ResourceManager.GetString("ProfitLoss_Profit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 爱原汁味的生活 的本地化字符串。
        /// </summary>
        public static string SystemName {
            get {
                return ResourceManager.GetString("SystemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增客户 的本地化字符串。
        /// </summary>
        public static string Title_AddCustomer {
            get {
                return ResourceManager.GetString("Title_AddCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增客户地址 的本地化字符串。
        /// </summary>
        public static string Title_AddCustomerAddress {
            get {
                return ResourceManager.GetString("Title_AddCustomerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增客户分组 的本地化字符串。
        /// </summary>
        public static string Title_AddCustomerGroup {
            get {
                return ResourceManager.GetString("Title_AddCustomerGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户 的本地化字符串。
        /// </summary>
        public static string Title_Customer {
            get {
                return ResourceManager.GetString("Title_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理地址 的本地化字符串。
        /// </summary>
        public static string Title_CustomerAddress {
            get {
                return ResourceManager.GetString("Title_CustomerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户明细 的本地化字符串。
        /// </summary>
        public static string Title_CustomerDetail {
            get {
                return ResourceManager.GetString("Title_CustomerDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户分组明细 的本地化字符串。
        /// </summary>
        public static string Title_CustomerGroupDetail {
            get {
                return ResourceManager.GetString("Title_CustomerGroupDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分组管理 的本地化字符串。
        /// </summary>
        public static string Title_CustomerGroupManagement {
            get {
                return ResourceManager.GetString("Title_CustomerGroupManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户管理 的本地化字符串。
        /// </summary>
        public static string Title_CustomerManagement {
            get {
                return ResourceManager.GetString("Title_CustomerManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑客户 的本地化字符串。
        /// </summary>
        public static string Title_EditCustomer {
            get {
                return ResourceManager.GetString("Title_EditCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑客户分组 的本地化字符串。
        /// </summary>
        public static string Title_EditCustomerGroup {
            get {
                return ResourceManager.GetString("Title_EditCustomerGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 首页 的本地化字符串。
        /// </summary>
        public static string Title_Index {
            get {
                return ResourceManager.GetString("Title_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户登录 的本地化字符串。
        /// </summary>
        public static string Title_Login {
            get {
                return ResourceManager.GetString("Title_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报损 的本地化字符串。
        /// </summary>
        public static string Title_Loss {
            get {
                return ResourceManager.GetString("Title_Loss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出库 - 选择产品 的本地化字符串。
        /// </summary>
        public static string Title_OutboundFirst {
            get {
                return ResourceManager.GetString("Title_OutboundFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出库 - 完成 的本地化字符串。
        /// </summary>
        public static string Title_OutboundFour {
            get {
                return ResourceManager.GetString("Title_OutboundFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出库记录 的本地化字符串。
        /// </summary>
        public static string Title_OutboundRecord {
            get {
                return ResourceManager.GetString("Title_OutboundRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出库 - 选择包装 的本地化字符串。
        /// </summary>
        public static string Title_OutboundSecond {
            get {
                return ResourceManager.GetString("Title_OutboundSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出库 - 日期、成本及备注 的本地化字符串。
        /// </summary>
        public static string Title_OutboundThird {
            get {
                return ResourceManager.GetString("Title_OutboundThird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外发订单 的本地化字符串。
        /// </summary>
        public static string Title_OutwardOrder {
            get {
                return ResourceManager.GetString("Title_OutwardOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品出库 的本地化字符串。
        /// </summary>
        public static string Title_ProductOutbound {
            get {
                return ResourceManager.GetString("Title_ProductOutbound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报益 的本地化字符串。
        /// </summary>
        public static string Title_Profit {
            get {
                return ResourceManager.GetString("Title_Profit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 采购 的本地化字符串。
        /// </summary>
        public static string Title_Purchase {
            get {
                return ResourceManager.GetString("Title_Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包装入库 的本地化字符串。
        /// </summary>
        public static string Title_Purchase_AddPack {
            get {
                return ResourceManager.GetString("Title_Purchase_AddPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品入库 的本地化字符串。
        /// </summary>
        public static string Title_Purchase_AddProduct {
            get {
                return ResourceManager.GetString("Title_Purchase_AddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包装库存 的本地化字符串。
        /// </summary>
        public static string Title_Purchase_Pack {
            get {
                return ResourceManager.GetString("Title_Purchase_Pack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品库存 的本地化字符串。
        /// </summary>
        public static string Title_Purchase_Product {
            get {
                return ResourceManager.GetString("Title_Purchase_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记录明细 的本地化字符串。
        /// </summary>
        public static string Title_RecordDetail {
            get {
                return ResourceManager.GetString("Title_RecordDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 销售订单 的本地化字符串。
        /// </summary>
        public static string Title_SaleOrder {
            get {
                return ResourceManager.GetString("Title_SaleOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数[{0}]无效 的本地化字符串。
        /// </summary>
        public static string Validate_ArgumentInValid {
            get {
                return ResourceManager.GetString("Validate_ArgumentInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入{0}，值为[{1} - {2}]之间的整数或小数。 的本地化字符串。
        /// </summary>
        public static string Validate_DecimalFieldRange {
            get {
                return ResourceManager.GetString("Validate_DecimalFieldRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入{0}，字数在[{1} - {2}]个之间。 的本地化字符串。
        /// </summary>
        public static string Validate_FieldLengthOverflow {
            get {
                return ResourceManager.GetString("Validate_FieldLengthOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入{0}，最多{1}个字。 的本地化字符串。
        /// </summary>
        public static string Validate_FieldMaxLength {
            get {
                return ResourceManager.GetString("Validate_FieldMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入{0}，值为[{1} - {2}]之间的整数。 的本地化字符串。
        /// </summary>
        public static string Validate_IntFieldRange {
            get {
                return ResourceManager.GetString("Validate_IntFieldRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入格式为yyyy-MM-dd的日期字符串。 的本地化字符串。
        /// </summary>
        public static string Validate_PleaseInputDateString {
            get {
                return ResourceManager.GetString("Validate_PleaseInputDateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入{0}。 的本地化字符串。
        /// </summary>
        public static string Validate_PleaseInputField {
            get {
                return ResourceManager.GetString("Validate_PleaseInputField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择{0}。 的本地化字符串。
        /// </summary>
        public static string Validate_PleaseSelectField {
            get {
                return ResourceManager.GetString("Validate_PleaseSelectField", resourceCulture);
            }
        }
    }
}
