//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySoft.PssS.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WebResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySoft.PssS.Web.Resources.WebResource", typeof(WebResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string Button_Ok {
            get {
                return ResourceManager.GetString("Button_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交 的本地化字符串。
        /// </summary>
        public static string Button_Submit {
            get {
                return ResourceManager.GetString("Button_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 。 的本地化字符串。
        /// </summary>
        public static string Flag_FullStop {
            get {
                return ResourceManager.GetString("Flag_FullStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个人中心 的本地化字符串。
        /// </summary>
        public static string HomeIndex_Title {
            get {
                return ResourceManager.GetString("HomeIndex_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未传入参数。 的本地化字符串。
        /// </summary>
        public static string Message_ArgumentIsNull {
            get {
                return ResourceManager.GetString("Message_ArgumentIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在载入... 的本地化字符串。
        /// </summary>
        public static string Message_Loading {
            get {
                return ResourceManager.GetString("Message_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交失败，错误信息 的本地化字符串。
        /// </summary>
        public static string Message_SubmitFailed {
            get {
                return ResourceManager.GetString("Message_SubmitFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包装 的本地化字符串。
        /// </summary>
        public static string Purchase_AddPack_Pack {
            get {
                return ResourceManager.GetString("Purchase_AddPack_Pack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包装入库 的本地化字符串。
        /// </summary>
        public static string Purchase_AddPack_Title {
            get {
                return ResourceManager.GetString("Purchase_AddPack_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成本数据为空。 的本地化字符串。
        /// </summary>
        public static string Purchase_AddProduct_CostDataIsNull {
            get {
                return ResourceManager.GetString("Purchase_AddProduct_CostDataIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存在空的成本项。 的本地化字符串。
        /// </summary>
        public static string Purchase_AddProduct_CostItemIsNull {
            get {
                return ResourceManager.GetString("Purchase_AddProduct_CostItemIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成本项金额必须大于等于0。 的本地化字符串。
        /// </summary>
        public static string Purchase_AddProduct_CostMoneyTip {
            get {
                return ResourceManager.GetString("Purchase_AddProduct_CostMoneyTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日期 的本地化字符串。
        /// </summary>
        public static string Purchase_AddProduct_Date {
            get {
                return ResourceManager.GetString("Purchase_AddProduct_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择日期 的本地化字符串。
        /// </summary>
        public static string Purchase_AddProduct_DateTip {
            get {
                return ResourceManager.GetString("Purchase_AddProduct_DateTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品 的本地化字符串。
        /// </summary>
        public static string Purchase_AddProduct_Item {
            get {
                return ResourceManager.GetString("Purchase_AddProduct_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择产品 的本地化字符串。
        /// </summary>
        public static string Purchase_AddProduct_ItemTip {
            get {
                return ResourceManager.GetString("Purchase_AddProduct_ItemTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择包装 的本地化字符串。
        /// </summary>
        public static string Purchase_AddProduct_ItemTip1 {
            get {
                return ResourceManager.GetString("Purchase_AddProduct_ItemTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入金额，单位：元 的本地化字符串。
        /// </summary>
        public static string Purchase_AddProduct_MoneyTip {
            get {
                return ResourceManager.GetString("Purchase_AddProduct_MoneyTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数量 的本地化字符串。
        /// </summary>
        public static string Purchase_AddProduct_Quantity {
            get {
                return ResourceManager.GetString("Purchase_AddProduct_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入数量，值为大于0的整数或小数。 的本地化字符串。
        /// </summary>
        public static string Purchase_AddProduct_QuantityTip {
            get {
                return ResourceManager.GetString("Purchase_AddProduct_QuantityTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入数量 的本地化字符串。
        /// </summary>
        public static string Purchase_AddProduct_QuantityTip1 {
            get {
                return ResourceManager.GetString("Purchase_AddProduct_QuantityTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入数量，单位： 的本地化字符串。
        /// </summary>
        public static string Purchase_AddProduct_QuantityTip2 {
            get {
                return ResourceManager.GetString("Purchase_AddProduct_QuantityTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        public static string Purchase_AddProduct_Remark {
            get {
                return ResourceManager.GetString("Purchase_AddProduct_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入备注信息，最多120个字 的本地化字符串。
        /// </summary>
        public static string Purchase_AddProduct_RemarkTip {
            get {
                return ResourceManager.GetString("Purchase_AddProduct_RemarkTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 供应方 的本地化字符串。
        /// </summary>
        public static string Purchase_AddProduct_Supplier {
            get {
                return ResourceManager.GetString("Purchase_AddProduct_Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入供应方名称，最多50个字 的本地化字符串。
        /// </summary>
        public static string Purchase_AddProduct_SupplierTip {
            get {
                return ResourceManager.GetString("Purchase_AddProduct_SupplierTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品入库 的本地化字符串。
        /// </summary>
        public static string Purchase_AddProduct_Title {
            get {
                return ResourceManager.GetString("Purchase_AddProduct_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有类型 的本地化字符串。
        /// </summary>
        public static string Purchase_Index_AllType {
            get {
                return ResourceManager.GetString("Purchase_Index_AllType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包装库存 的本地化字符串。
        /// </summary>
        public static string Purchase_Index_PackTitle {
            get {
                return ResourceManager.GetString("Purchase_Index_PackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品库存 的本地化字符串。
        /// </summary>
        public static string Purchase_Index_ProductTitle {
            get {
                return ResourceManager.GetString("Purchase_Index_ProductTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 爱原汁味的生活 的本地化字符串。
        /// </summary>
        public static string SystemName {
            get {
                return ResourceManager.GetString("SystemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 立即登录 的本地化字符串。
        /// </summary>
        public static string UserLogin_LoginButton {
            get {
                return ResourceManager.GetString("UserLogin_LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手机号或密码错误，请重新输入。 的本地化字符串。
        /// </summary>
        public static string UserLogin_LoginError {
            get {
                return ResourceManager.GetString("UserLogin_LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入您的手机号 的本地化字符串。
        /// </summary>
        public static string UserLogin_MoblieTip {
            get {
                return ResourceManager.GetString("UserLogin_MoblieTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入您的密码 的本地化字符串。
        /// </summary>
        public static string UserLogin_PasswordTip {
            get {
                return ResourceManager.GetString("UserLogin_PasswordTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户登录 的本地化字符串。
        /// </summary>
        public static string UserLogin_Title {
            get {
                return ResourceManager.GetString("UserLogin_Title", resourceCulture);
            }
        }
    }
}
